name: Go CI

# 起動イベント指定
on: [push, pull_request]

# ジョブ定義
jobs:
  build:
    name: Build
    # ジョブが実行されるGitHubホストランナーを指定
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
    # 指定したバージョンのGoをセットアップ
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test
      run: go test -v ./...

